apiVersion: v1
kind: Service
metadata:
  name: master-nodeport
  namespace: remote-code-executor
spec:
  type: NodePort
  selector:
    app: master
  ports:
    - protocol: TCP
      name: http
      port: 3000         # The port exposed by the Service
      targetPort: 3000   # The port on the Pod
      nodePort: 32000    # Static port on the Node (between 30000-32767)
