apiVersion: v1
kind: Service
metadata:
  name: master-clusterip
  namespace: remote-code-executor
spec:
  type: ClusterIP
  selector:
    app: master
  ports:
    - protocol: TCP
      port: 9001          # RPC requests
      targetPort: 9001    # Pod's container port for RPC
