// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: executions.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Executions_GetExecution_FullMethodName = "/pb.Executions/GetExecution"
)

// ExecutionsClient is the client API for Executions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecutionsClient interface {
	GetExecution(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionTask, error)
}

type executionsClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionsClient(cc grpc.ClientConnInterface) ExecutionsClient {
	return &executionsClient{cc}
}

func (c *executionsClient) GetExecution(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionTask)
	err := c.cc.Invoke(ctx, Executions_GetExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutionsServer is the server API for Executions service.
// All implementations must embed UnimplementedExecutionsServer
// for forward compatibility.
type ExecutionsServer interface {
	GetExecution(context.Context, *ExecutionRequest) (*ExecutionTask, error)
	mustEmbedUnimplementedExecutionsServer()
}

// UnimplementedExecutionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutionsServer struct{}

func (UnimplementedExecutionsServer) GetExecution(context.Context, *ExecutionRequest) (*ExecutionTask, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExecution not implemented")
}
func (UnimplementedExecutionsServer) mustEmbedUnimplementedExecutionsServer() {}
func (UnimplementedExecutionsServer) testEmbeddedByValue()                    {}

// UnsafeExecutionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutionsServer will
// result in compilation errors.
type UnsafeExecutionsServer interface {
	mustEmbedUnimplementedExecutionsServer()
}

func RegisterExecutionsServer(s grpc.ServiceRegistrar, srv ExecutionsServer) {
	// If the following call pancis, it indicates UnimplementedExecutionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Executions_ServiceDesc, srv)
}

func _Executions_GetExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionsServer).GetExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Executions_GetExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionsServer).GetExecution(ctx, req.(*ExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Executions_ServiceDesc is the grpc.ServiceDesc for Executions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Executions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Executions",
	HandlerType: (*ExecutionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExecution",
			Handler:    _Executions_GetExecution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "executions.proto",
}
